### ISSUE TITLE
add compose file example

### ISSUE THREAD

**Issue by mschn** [mschn/voyage#9]
ie

```
services:
  voyage:
    image: "mschnr/voyage"
    container_name: "voyage"
    ports:
      - "3001:3003"
    volumes:
      - "/home/mschn:/files"
    environment:
      VOYAGE_ROOT: "/files"

```
